### PR TITLE
foxed it.

### PR DESCRIPTION
**Pull request by foxieze**
i foxed your horrible code now pay me c:

### CODE REVIEW

**Comment by PipeWarp** [comment]
Thanks for fixing my horrible code, but I think your "I" key is broken.

**Comment by foxieze** [comment]
shut up. o am perfectly happy woth usong o instead of o

**Comment by PipeWarp** [comment]
image

**Comment by foxieze** [comment]
fock yoo. yes o have goven op on both my o and my o keys

**Comment by PipeWarp** [comment]
ok

**Comment by foxieze** [comment]
o > k

**Pull request merged**
